package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import DBConnection.DBConnection;
import model.Amenity;

public class AmenityDAO {

    // List all active amenities.
    public List<Amenity> getAllActiveAmenities() {

        List<Amenity> list = new ArrayList<>();

        String sql =
                "SELECT AMENITYID, AMENITYNAME, STATUS " +
                "FROM AMENITY " +
                "WHERE STATUS = 'ACTIVE' " +
                "ORDER BY AMENITYID DESC";

        try (
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery()
        ) {

            while (rs.next()) {

                Amenity amenity = new Amenity();

                amenity.setAmenityId(
                        rs.getInt("AMENITYID"));

                amenity.setAmenityName(
                        rs.getString("AMENITYNAME"));

                amenity.setStatus(
                        rs.getString("STATUS"));

                list.add(amenity);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return list;
    }

    // List active amenities belonging to one accommodation.
    public List<Amenity> getAmenitiesByAccommodation(
            String accommodationId) {

        List<Amenity> list = new ArrayList<>();

        String sql =
                "SELECT AMENITYID, AMENITYNAME, STATUS, ACCOMMODATIONID " +
                "FROM AMENITY " +
                "WHERE ACCOMMODATIONID = ? " +
                "AND STATUS = 'ACTIVE' " +
                "ORDER BY AMENITYID";

        try (
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql)
        ) {

            ps.setString(
                    1,
                    accommodationId.trim());

            try (ResultSet rs = ps.executeQuery()) {

                while (rs.next()) {

                    Amenity amenity = new Amenity();

                    amenity.setAmenityId(
                            rs.getInt("AMENITYID"));

                    amenity.setAmenityName(
                            rs.getString("AMENITYNAME"));

                    amenity.setStatus(
                            rs.getString("STATUS"));

                    list.add(amenity);
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return list;
    }

    /*
     * Add one amenity to an accommodation.
     * AMENITYID is generated by AMENITY_SEQ.NEXTVAL.
     * Empty textbox is treated as optional and returns true.
     */
    public boolean addAmenityToAccommodation(
            String amenityName,
            String accommodationId) {

        if (isBlank(amenityName)) {
            return true;
        }

        if (isBlank(accommodationId)) {
            return false;
        }

        String cleanAmenityName =
                amenityName.trim();

        String cleanAccommodationId =
                accommodationId.trim();

        String duplicateSql =
                "SELECT COUNT(*) " +
                "FROM AMENITY " +
                "WHERE UPPER(AMENITYNAME) = UPPER(?) " +
                "AND ACCOMMODATIONID = ? " +
                "AND STATUS = 'ACTIVE'";

        String insertSql =
                "INSERT INTO AMENITY " +
                "(AMENITYID, AMENITYNAME, ACCOMMODATIONID, STATUS) " +
                "VALUES (AMENITY_SEQ.NEXTVAL, ?, ?, 'ACTIVE')";

        try (Connection conn = DBConnection.getConnection()) {

            try (
                PreparedStatement duplicatePs =
                        conn.prepareStatement(duplicateSql)
            ) {

                duplicatePs.setString(
                        1,
                        cleanAmenityName);

                duplicatePs.setString(
                        2,
                        cleanAccommodationId);

                try (ResultSet rs = duplicatePs.executeQuery()) {

                    if (rs.next() && rs.getInt(1) > 0) {
                        // Amenity already exists for this accommodation.
                        return true;
                    }
                }
            }

            try (
                PreparedStatement insertPs =
                        conn.prepareStatement(insertSql)
            ) {

                insertPs.setString(
                        1,
                        cleanAmenityName);

                insertPs.setString(
                        2,
                        cleanAccommodationId);

                return insertPs.executeUpdate() > 0;
            }

        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /*
     * Transaction version, used when accommodation update and
     * amenity inserts should share the same Connection.
     */
    public boolean addAmenityToAccommodation(
            Connection conn,
            String amenityName,
            String accommodationId)
            throws SQLException {

        if (isBlank(amenityName)) {
            return true;
        }

        if (conn == null || isBlank(accommodationId)) {
            return false;
        }

        String cleanAmenityName =
                amenityName.trim();

        String cleanAccommodationId =
                accommodationId.trim();

        String duplicateSql =
                "SELECT COUNT(*) " +
                "FROM AMENITY " +
                "WHERE UPPER(AMENITYNAME) = UPPER(?) " +
                "AND ACCOMMODATIONID = ? " +
                "AND STATUS = 'ACTIVE'";

        String insertSql =
                "INSERT INTO AMENITY " +
                "(AMENITYID, AMENITYNAME, ACCOMMODATIONID, STATUS) " +
                "VALUES (AMENITY_SEQ.NEXTVAL, ?, ?, 'ACTIVE')";

        try (
            PreparedStatement duplicatePs =
                    conn.prepareStatement(duplicateSql)
        ) {

            duplicatePs.setString(
                    1,
                    cleanAmenityName);

            duplicatePs.setString(
                    2,
                    cleanAccommodationId);

            try (ResultSet rs = duplicatePs.executeQuery()) {

                if (rs.next() && rs.getInt(1) > 0) {
                    return true;
                }
            }
        }

        try (
            PreparedStatement insertPs =
                    conn.prepareStatement(insertSql)
        ) {

            insertPs.setString(
                    1,
                    cleanAmenityName);

            insertPs.setString(
                    2,
                    cleanAccommodationId);

            return insertPs.executeUpdate() > 0;
        }
    }

    // Update amenity name.
    public boolean updateAmenity(Amenity amenity) {

        String sql =
                "UPDATE AMENITY " +
                "SET AMENITYNAME = ? " +
                "WHERE AMENITYID = ?";

        try (
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql)
        ) {

            ps.setString(
                    1,
                    amenity.getAmenityName().trim());

            ps.setInt(
                    2,
                    amenity.getAmenityId());

            return ps.executeUpdate() > 0;

        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    // Soft-delete amenity.
    public boolean archiveAmenity(int amenityId) {

        String sql =
                "UPDATE AMENITY " +
                "SET STATUS = 'ARCHIVED' " +
                "WHERE AMENITYID = ?";

        try (
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql)
        ) {

            ps.setInt(
                    1,
                    amenityId);

            return ps.executeUpdate() > 0;

        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    private boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }
}